---
- name: Pull frontend builder image
  ansible.builtin.shell: |
    set -e
    {{ compose_cmd }} -f /home/{{ ansible_user }}/nuspace/infra/prod.docker-compose.yml build frontend-builder
  args:
    executable: /bin/bash
  when: (frontend_changed | default(false)) | bool or (force_frontend_build | default(false)) | bool

- name: Run frontend build (frontend-builder)
  ansible.builtin.command: >
    {{ compose_cmd }} -f /home/{{ ansible_user }}/nuspace/infra/prod.docker-compose.yml
    up --no-deps frontend-builder
  when: (frontend_changed | default(false)) | bool or (force_frontend_build | default(false)) | bool

- name: Recreate nginx service
  ansible.builtin.command: >
    {{ compose_cmd }} -f /home/{{ ansible_user }}/nuspace/infra/prod.docker-compose.yml
    up --no-deps -d nginx
  when: (nginx_changed | default(false)) | bool or (container_analysis is defined and 'nginx' in container_analysis.stdout)


