---
- name: Create SSL directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/nuspace/ssl"
    state: directory
    mode: '0755'

- name: Pull cloudflare.crt from Google Secret Manager atomically
  ansible.builtin.shell: |
    set -euo pipefail
    export PATH="/root/google-cloud-sdk/bin:$PATH"
    tmpfile=$(mktemp)
    gcloud secrets versions access latest --secret="cloudflare-crt" --project="{{ gcp_project }}" > "$tmpfile"
    grep -q -- "-----BEGIN CERTIFICATE-----" "$tmpfile"
    install -m 0600 -o {{ ansible_user }} -g {{ ansible_user }} "$tmpfile" /home/{{ ansible_user }}/nuspace/ssl/cloudflare.crt
    rm -f "$tmpfile"
  args:
    executable: /bin/bash

- name: Pull cloudflare.key from Google Secret Manager atomically
  ansible.builtin.shell: |
    set -euo pipefail
    export PATH="/root/google-cloud-sdk/bin:$PATH"
    tmpfile=$(mktemp)
    gcloud secrets versions access latest --secret="cloudflare-key" --project="{{ gcp_project }}" > "$tmpfile"
    grep -Eq -- "-----BEGIN .*PRIVATE KEY-----" "$tmpfile"
    install -m 0600 -o {{ ansible_user }} -g {{ ansible_user }} "$tmpfile" /home/{{ ansible_user }}/nuspace/ssl/cloudflare.key
    rm -f "$tmpfile"
  args:
    executable: /bin/bash

- name: Set proper permissions for SSL files
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0600'
  loop:
    - "/home/{{ ansible_user }}/nuspace/ssl/cloudflare.crt"
    - "/home/{{ ansible_user }}/nuspace/ssl/cloudflare.key"

- name: Pull .env from Google Secret Manager
  ansible.builtin.shell: |
    export PATH="/root/google-cloud-sdk/bin:$PATH"
    gcloud secrets versions access latest --secret="nuspace-env" --project="{{ gcp_project }}" > /home/{{ ansible_user }}/nuspace/infra/.env
  args:
    executable: /bin/bash

- name: Set proper permissions for .env file
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/nuspace/infra/.env"
    mode: '0600'


