---
- name: Deploy Docker Containers
  hosts: webservers
  become: true
  strategy: free
  gather_facts: false
  vars:
    docker_username: "{{ docker_user }}"
    docker_password: "{{ docker_pass }}"
    image_tag: "{{ docker_image_tag }}"
    gcp_project: "{{ gcp_project_var }}"

  tasks:
    - name: Include prerequisites role
      ansible.builtin.include_role:
        name: prerequisites

    - name: Docker Hub login
      ansible.builtin.shell: |
        set -e
        echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin
      args:
        executable: /bin/bash
      no_log: true

    - name: Sync repository
      ansible.builtin.include_role:
        name: repo_sync

    - name: Retrieve secrets and env files
      ansible.builtin.include_role:
        name: secrets

    - name: Analyze running containers
      ansible.builtin.include_role:
        name: container_analysis

    - name: Backend tasks (migrations, fastapi, celery-worker)
      ansible.builtin.include_role:
        name: backend

    - name: Frontend tasks (build dist and reload nginx)
      ansible.builtin.include_role:
        name: frontend

    - name: Infra services (redis, rabbitmq, prometheus, grafana, loki, alloy, alertmanager, wireguard, meilisearch)
      ansible.builtin.include_role:
        name: infra_services

    - name: Post tasks (cleanup)
      ansible.builtin.include_role:
        name: post_tasks
