---
- name: Deploy Docker Containers
  hosts: webservers
  become: true
  strategy: free
  gather_facts: false
  vars:
    docker_username: "{{ docker_user }}"
    docker_password: "{{ docker_pass }}"
    ansible_user: "{{ ansible_user_var }}"
    image_tag: "{{ docker_image_tag }}"

  tasks:
    - name: Include prerequisites role
      ansible.builtin.include_role:
        name: prerequisites

    - name: Docker Hub login
      ansible.builtin.shell: |
        set -e
        echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin
      args:
        executable: /bin/bash
      no_log: true

    - name: Sync repository
      ansible.builtin.include_role:
        name: repo_sync

    - name: Retrieve secrets and env files
      ansible.builtin.include_role:
        name: secrets

    - name: Analyze running containers
      ansible.builtin.include_role:
        name: container_analysis

    - name: Backend tasks (migrations and services)
      ansible.builtin.include_role:
        name: backend

    - name: Frontend tasks (build and nginx)
      ansible.builtin.include_role:
        name: frontend

    - name: Infra services (redis, rabbitmq, prometheus, grafana, loki, alloy, alertmanager, wireguard)
      ansible.builtin.include_role:
        name: infra_services

    - name: Post tasks
      ansible.builtin.include_role:
        name: post_tasks
