name: Terraform Stage Deploy

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          token: ${{ github.token }}
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            nginx:
              - 'infra/nginx/**'
            redis:
              - 'infra/redis/**'
            rabbitmq:
              - 'infra/rabbitmq/**'
            prometheus:
              - 'infra/prometheus/**'
            grafana:
              - 'infra/grafana/**'
            loki:
              - 'infra/loki/**'
            alloy:
              - 'infra/alloy/**'
            alertmanager:
              - 'infra/alertmanager/**'
            wireguard:
              - 'infra/wireguard/**'
            compose:
              - 'infra/prod.docker-compose.yml'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      # --- Build FastAPI Image ---
      - name: Build and Push FastAPI Image
        if: steps.changes.outputs.backend == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: kamikadze24/fastapi:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=fastapi
          cache-to: type=gha,mode=max,scope=fastapi

      # --- Build Celery Worker Image ---
      - name: Build and Push Celery Worker Image
        if: steps.changes.outputs.backend == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile_celery
          push: true
          tags: kamikadze24/celeryworker:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=celeryworker
          cache-to: type=gha,mode=max,scope=celeryworker

      # --- Build Frontend Builder Image ---
      - name: Build and Push Frontend Builder Image
        if: steps.changes.outputs.frontend == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile_static_builder
          push: true
          tags: kamikadze24/frontendbuilder:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible and Google Cloud SDK
        run: |
          pip install ansible
          curl -sSL https://sdk.cloud.google.com | bash
          echo "$HOME/google-cloud-sdk/bin" >> $GITHUB_PATH

      - name: Authenticate with Google Cloud
        run: |
          # Clean and decode the base64 service account key
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' | tr -d '\n\r' | sed 's/[[:space:]]//g' | sed 's/%$//' | base64 -d > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project nuspace-staging

      - name: Get VM information and Docker credentials from Secret Manager
        id: secrets
        run: |
          # Get VM instance details using the service account
          VM_IP=$(gcloud compute instances describe nuspace-instance --zone=europe-central2-a --format="value(networkInterfaces[0].accessConfigs[0].natIP)")
          VM_NAME="nuspace-instance"
          SA_USERNAME=$(gcloud compute os-login describe-profile --format="value(posixAccounts[0].username)")
          DOCKER_USERNAME=$(gcloud secrets versions access latest --secret="docker-username")
          DOCKER_PASSWORD=$(gcloud secrets versions access latest --secret="docker-password")
          echo "ANSIBLE_HOST=$VM_IP" >> $GITHUB_OUTPUT
          echo "VM_NAME=$VM_NAME" >> $GITHUB_OUTPUT
          echo "ANSIBLE_USER=$SA_USERNAME" >> $GITHUB_OUTPUT
          echo "DOCKER_USERNAME=$DOCKER_USERNAME" >> $GITHUB_OUTPUT
          echo "::add-mask::$DOCKER_PASSWORD"
          echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> $GITHUB_OUTPUT

      - name: Check if containers are running on VM
        id: container_check
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
        run: |
          # Test connection and check container status using instance name
          gcloud compute ssh ${{ steps.secrets.outputs.VM_NAME }} --zone=europe-central2-a --command="docker ps --format 'table {{.Names}}\t{{.Status}}'" --ssh-flag="-o ConnectTimeout=10" --quiet > /tmp/container_status.txt 2>/dev/null || echo "Connection failed" > /tmp/container_status.txt
          
          # Check if expected containers are running
          if grep -q "fastapi\|celery-worker\|nginx\|redis\|rabbitmq\|prometheus\|grafana\|loki\|alloy\|alertmanager\|wireguard" /tmp/container_status.txt; then
            echo "containers_running=true" >> $GITHUB_OUTPUT
          else
            echo "containers_running=false" >> $GITHUB_OUTPUT
          fi
          
          # Always run if there are code changes
          if [[ "${{ steps.changes.outputs.backend }}" == "true" || "${{ steps.changes.outputs.frontend }}" == "true" || "${{ steps.changes.outputs.nginx }}" == "true" || "${{ steps.changes.outputs.redis }}" == "true" || "${{ steps.changes.outputs.rabbitmq }}" == "true" || "${{ steps.changes.outputs.prometheus }}" == "true" || "${{ steps.changes.outputs.grafana }}" == "true" || "${{ steps.changes.outputs.loki }}" == "true" || "${{ steps.changes.outputs.alloy }}" == "true" || "${{ steps.changes.outputs.alertmanager }}" == "true" || "${{ steps.changes.outputs.wireguard }}" == "true" || "${{ steps.changes.outputs.compose }}" == "true" ]]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Ansible configuration
        run: |
          cat > ansible/ansible.cfg << EOF
          [defaults]
          remote_tmp = /tmp
          local_tmp = /tmp
          host_key_checking = False
          timeout = 60
          gathering = explicit
          fact_caching = memory
          ansible_managed = Ansible managed
          
          [ssh_connection]
          ssh_args = 
          control_path_dir = /tmp
          EOF

      - name: Create inventory file
        run: |
          cat > ansible/inventory.yml << EOF
          ---
          all:
            children:
              webservers:
                hosts:
                  ${{ steps.secrets.outputs.VM_NAME }}:
                    ansible_host: ${{ steps.secrets.outputs.ANSIBLE_HOST }}
                    ansible_user: ${{ steps.secrets.outputs.ANSIBLE_USER }}
                    ansible_ssh_private_key_file: ~/.ssh/google_compute_engine
                    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
                    ansible_become: yes
                    ansible_become_method: sudo
                    ansible_remote_tmp: /tmp
                    ansible_shell_type: sh
          EOF

      - name: Run Ansible Playbook
        if: |
          steps.container_check.outputs.should_deploy == 'true' ||
          steps.container_check.outputs.containers_running == 'false'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_REMOTE_TMP: /tmp
          ANSIBLE_LOCAL_TMP: /tmp
        run: |
          # Test OS Login connection and prepare environment
          gcloud compute ssh ${{ steps.secrets.outputs.VM_NAME }} --zone=europe-central2-a --command="echo 'OS Login configured'" --ssh-flag="-o ConnectTimeout=10" --quiet || true
          
          # Run the Ansible playbook
          cd ansible && ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook stage.playbook.yml \
            --inventory inventory.yml \
            --extra-vars "docker_image_tag=${{ steps.meta.outputs.version }} ansible_user_var=${{ steps.secrets.outputs.ANSIBLE_USER }} docker_user=${{ steps.secrets.outputs.DOCKER_USERNAME }} docker_pass=${{ steps.secrets.outputs.DOCKER_PASSWORD }} backend_changed=${{ steps.changes.outputs.backend }} frontend_changed=${{ steps.changes.outputs.frontend }} nginx_changed=${{ steps.changes.outputs.nginx }} redis_changed=${{ steps.changes.outputs.redis }} rabbitmq_changed=${{ steps.changes.outputs.rabbitmq }} prometheus_changed=${{ steps.changes.outputs.prometheus }} grafana_changed=${{ steps.changes.outputs.grafana }} loki_changed=${{ steps.changes.outputs.loki }} alloy_changed=${{ steps.changes.outputs.alloy }} alertmanager_changed=${{ steps.changes.outputs.alertmanager }} wireguard_changed=${{ steps.changes.outputs.wireguard }} compose_changed=${{ steps.changes.outputs.compose }}"
